### ISSUE TITLE
"Qualifications" also eigene Entität

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#12]

**Comment by maxbeier** [comment]
Kommen denn noch weitere Gruppen dazu?

**Comment by maxbeier** [comment]
Kommen eurer Meinung nach noch weitere Qualifikationen hinzu?

**Comment by Cadusredefine** [comment]
ggf. im laufe der Zeit.

**Comment by maxbeier** [comment]
Ok, dann würde ich das erstmal doch nicht zu umbauen, sondern anfügen, wenn was Neues dazu kommt.
