### ISSUE TITLE
passwort

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#17]
sag mal, wäre das perspektivisch, nicht jetzt möglich die logins über passwörter laufen zu lassen? 

seb dazu:"und ja, generell ist es einfacher, mit passwörtern zu arbeiten...würde ich max fragen, ob das später umstellbar ist...weil, wenn du unterwegs bist und deinen rechner nicht bei hast, kannst du dich nur schwer von anderen rechnern einloggen..."

**Comment by maxbeier** [comment]
Hmm, habe extra den Token-Mechanismus entwickelt, weil es meiner Meinung nach gerade nicht einfacher ist, mit Passwörtern zu arbeiten. Weil Leute die vergessen, zurücksetzen und auf ein neues warten, das sie dann irgendwann wieder vergessen.

Letztlich ist das Passwort das Passwort zum Mail-Account – denn wer in seinen Mail-Account kommt, der hat den Link und darüber kann man sich immer automatisch einloggen.

**Comment by Cadusredefine** [comment]
Ist sowieso vorerst unwichtig. Ich quatsch nochmal mit seb sobald er wieder da ist. Hat auf jeden Fall gerade keine Priorität. 

Am 10. März 2017 16:39:28 MEZ schrieb Max Beier <notifications@github.com>:
>Hmm, habe extra den Token-Mechanismus entwickelt, weil es meiner
>Meinung nach gerade nicht einfacher ist, mit Passwörtern zu arbeiten.
>Weil Leute die vergessen, zurücksetzen und auf ein neues warten, das
>sie dann irgendwann wieder vergessen.
>
>Letztlich ist das Passwort das Passwort zum Mail-Account – denn wer in
>seinen Mail-Account kommt, der hat den Link und darüber kann man sich
>immer automatisch einloggen.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cadus/crewing/issues/17#issuecomment-285701082

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by maxbeier** [comment]
Token-System bleibt vorerst so.
