### ISSUE TITLE
Speichern Safari funktioniert nicht 

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#23]
Wir haben von einigen Leuten Mails bekommen, dass das Speichern nicht funkrioniert. 
Haben es auf mehreren PCs probiert (in verschiedenen Browsern). Chrome und Firefox funktionieren.

Safari nicht.

**Comment by maxbeier** [comment]
Habe es eben bei mir in Safari getestet und konnte speichern – kannst du mir mehr zu dem Fehler sagen, z.B. welche Felder betroffen waren?

**Comment by Cadusredefine** [comment]
der gesamte speichervorgang konnte nicht abgeschlossen werden. 

Wurde angezeigt, dass gearbeitet wird, allerdings endlos. ist weiter nichts mehr passiert.. 

und, eine andere person konnte nicht mal auf "change data" klicken - keine reaktion,

**Comment by maxbeier** [comment]
Hmm, ich kann in den Logs nichts dazu finden (nur jemand namens Indra hat anscheinend versucht, sich mehrmals anzumelden, aber das wird in #14 behandelt.)

Kannst du versuchen, rauszubekommen, welche Browser die Personen benutzen?

**Comment by Cadusredefine** [comment]
Browser = Safari, oder brauchst du ne andere info?

indra konnte nicht auf "change data" klicken. 

Bei Christoph konnte der speichervorgang nicht abgeschlossen werden, aber wir testen das nochmal eben.

**Comment by Cadusredefine** [comment]
christoph hat es jetzt nochmal versucht, hat geklappt.

**Comment by maxbeier** [comment]
Ok – klappt es bei Indra auch?

**Comment by Cadusredefine** [comment]
indra ist gerade nicht mehr im Büro, ich würde sie morgen nochmal testen lassen.

**Comment by maxbeier** [comment]
Hat's geklappt?

**Comment by Cadusredefine** [comment]
ja. danke
