### ISSUE TITLE
Vorschaubilder von Uploads werden im Backend nicht angezeigt

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#26]
man sieht nur den dateiname, aber keine bildvorschau.. 

hatten wir schon mal drüber gesprochen.. gibt es dafür schon ein Issue?

**Comment by maxbeier** [comment]
Im Frontend schon, im Backend nicht. Ich schaue mal, ob ich das im Backend einbauen kann.

**Comment by Cadusredefine** [comment]
wie siehts denn eigentlich hiermit aus? Klappt das?

**Comment by maxbeier** [comment]
Noch nicht.

**Comment by maxbeier** [comment]
Ist drin. Passt es so?

**Comment by Cadusredefine** [comment]
ja
