### ISSUE TITLE
Citizenship / dual citizenship

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#28]
dual citizenship, yes / no? if yes, which? 

kannst du das noch einbauen, bitte.

**Comment by Cadusredefine** [comment]
dual citizenship, yes / no? if yes, which? 

kannst du das noch einbauen, bitte.

**Comment by maxbeier** [comment]
Da es bisher keine Angabe zur Staatsangehörigkeit gibt, habe ich eine angelegt.

![screen shot 2017-03-24 at 15 22 37](https://cloud.githubusercontent.com/assets/236774/24298313/dfe2e874-10a5-11e7-8680-f9727e5c8784.png)

Falls ihr wirklich nur eine Angabe zur doppelten Angehörigkeit möchtet: Wo soll das hin?

**Comment by Cadusredefine** [comment]
was meinst du mit "einer angabe"?

**Comment by maxbeier** [comment]
Mit Angabe meine ich eine Information, die angegeben wird. Anders ausgedrückt: Es gab bisher kein Feld dazu.

**Comment by Cadusredefine** [comment]
gibt es ne möglichkeit, dass man Citizenship und dual C. aufteilt? bei dual dann die möglichkeit hat anzuklicken: "no" /"yes" "if yes, which?"

**Comment by maxbeier** [comment]
Ich kann einfach zwei Felder einbauen, eins für die erste uns eins für die zweite Staatsangehörigkeit.

**Comment by Cadusredefine** [comment]
super.

**Comment by maxbeier** [comment]
Ist drin. Passt es so?

**Comment by Cadusredefine** [comment]
ja
