### ISSUE TITLE
Filter: Availabilities 

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#29]
ist das möglich? wäre wichtig für uns. danke

**Comment by maxbeier** [comment]
Derzeit nicht. Hatte damals schon mit Christoph darüber gesprochen und da war meiner Erinnerung nach die Idee, dass ihr eine eigene Seite zur Einsatzplanung bekommt. Dort werden Missionen angelegt und nach Eingabe des Zeitraumes können die dann verfügbaren Helfer ausgewählt werden.

Daher zur Klärung: Wollt ihr sicher einen Filter im Backend? Wäre wahrscheinlich viel Aufwand.

**Comment by Cadusredefine** [comment]
das heißt, diese seite müsste noch gemacht werden? In der App selber gibt es momentan keine Möglichkeit nach Verfügbarkeiten zu filtern auch nicht unter Missions, korrekt? 

ich bespreche das mal mit Seb

**Comment by maxbeier** [comment]
Ja

**Comment by Cadusredefine** [comment]
okay, davon hat Christoph mir leider nichts gesagt. Kannst du mir sagen, wer diese Seite machen sollte? Oder ob da schon irgendwas exsistiert?

**Comment by maxbeier** [comment]
Die Seite muss ich irgendwann bauen, habe ich aber noch nicht.

**Comment by Cadusredefine** [comment]
bauen.. sorry!
Okay, ist mir wirklich unangenehm dich das zu fragen und möchte da auch keinen Stress machen - aber kannst du einschätzen, wann das ungefähr sein wird? Klingt ja doch nach mehr aufwand.. Danke dir!

**Comment by maxbeier** [comment]
So, einiges abgearbeitet. Wenn das alles von eurer Seite aus abgesegnet wurde, mache ich mich an besagtes Feature – habe es in #33 kurz beschrieben.

Ich weiß nicht, wann ich das nächste Mal dazu komme (vielleicht Ende nächster Woche) – könnt ihr bis dahin in dem neuen Ticket grob skizzieren, wie die Missions-Planung von eurer Seite aus laufen soll?

Ich schließe das Ticket hier schon mal.
