### ISSUE TITLE
Linux 

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#30]
Info: Die seite scheint mit einem Linux Betriebssystem nicht zu funktionieren.

**Comment by maxbeier** [comment]
Die Funktionalität der Seite hat nichts mit dem Betriebssystem zu tun, sondern nur mit dem Browser.

Wenn es ein Problem gab, kannst du mir mehr darüber sagen?

**Comment by Cadusredefine** [comment]
ok, ne mehr kann ich dazu nicht sagen. danke.
