### ISSUE TITLE
driver's license / international driver's license

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#31]
wäre auch super, wenn man dafür noch ein feld hätte. 

auch für LKW

**Comment by maxbeier** [comment]
Verstehe ich nicht. Also du möchtest vier Checkboxen:
- Driver's Licence
- Truck Driver's Licence
- International Driver's Licence
- International Truck Driver's Licence

?

**Comment by Cadusredefine** [comment]
jep, das wäre die Wunschlösung.

**Comment by maxbeier** [comment]
Ist drin. Passt es so?

**Comment by Cadusredefine** [comment]
ja
