### ISSUE TITLE
Speichern erst möglich, wenn Formular ausgefüllt ist

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#34]
die meisten kriegen es nicht hin, das Formular tatsächlich auszufüllen. Ist es möglich, dass man erst speichern kann,wenn die Person es ausgefüllt hat?

**Comment by maxbeier** [comment]
"Kriegen es nicht hin" nicht aus technischer Sicht, oder? Also sie machen es einfach nicht?

Man könnte das Speichern erst erlauben, wenn alle oder eine vorher definierte Gruppe von Angaben ausgefüllt wurden, aber das könnte auch bevormundend sein bzw. vielleicht können Sie es zu Zeitpunkt X auch nicht weiter ausfüllen.

Naja, die kurze Antwort ist "Ja".

**Comment by Cadusredefine** [comment]
nein, nicht aus technischer Sicht. 
Ich weiß was du meinst, allerdings können wir so nicht damit arbeiten und da hat keiner etwas von. Vorher definierte Gruppen klingt super, ich würde das besprechen und mich dann bei dir melden.

**Comment by maxbeier** [comment]
Ok, das ist schnell gemacht – schick mir einfach eine Liste der Bezeichnungen der obligatorischen Felder und ich baue das ein.

**Comment by Cadusredefine** [comment]
kannst du das für alles einbauen außer für availabilities, emergency contact, notes und foto. 

availabilities ergibt einfach keinen sinn, dass das direkt angegeben werden muss.

**Comment by maxbeier** [comment]
Habe besagte Felder (bis auf die Uploads) als `required` markiert, mit einem blauen Rahmen gekennzeichnet und ein Info-Feld hinzugefügt. Zudem ist der Speichern-Button jetzt immer unten sichtbar (in Chrome, Firefox und Safari).

Bitte prüfen, ob es so passt und dann hier gegebenenfalls schreiben oder das Ticket schließen, wenn alles ok ist.
