### ISSUE TITLE
Have you every been in exceptional psychological condition?

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#35]
kannst du unter dem Punkt "Condition" bei der frage, die du im Betreff siehst aus "every" "ever" machen, bitte.

**Comment by Cadusredefine** [comment]
bzw. austauschen und diesen Satz zu nehmen: "Have you ever experienced mental distress or even a state of mental emergency after an exceptional challenging situation"

**Comment by maxbeier** [comment]
Ist im nächsten Update drin.
