### ISSUE TITLE
Group&Q

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#36]
gibt es die Möglichkeit, dass der/die Admin bei der Missionplanung noch eine Person als  "In-field-leader" (IFL) und Head of Mission (HoM) ernennen kann ? kannst du das irgendwas einbauen?

**Comment by maxbeier** [comment]
Also aktuell geht das nicht.

So in etwa?

![screen shot 2017-05-09 at 15 16 40](https://cloud.githubusercontent.com/assets/236774/25852709/8ecc1548-34ca-11e7-9c9e-c514f2f1ebc5.png)

Und wenn ja, soll das sonst noch Auswirkungen haben? Soll beispielsweise die Person das auch sehen? Sollen die anderen Teilnehmer das sehen?

**Comment by Cadusredefine** [comment]
ja. gerne soll die perosn und die anderen das sehen.

**Comment by Cadusredefine** [comment]
kannst du noch "logistician" anlegen?

**Comment by maxbeier** [comment]
Also Gruppe oder spezielle Position wie Head of Mission?

**Comment by maxbeier** [comment]
So?

![screen shot 2017-05-10 at 14 29 13](https://cloud.githubusercontent.com/assets/236774/25898597/126ab068-358d-11e7-8cc4-9a3a0d3454f2.png)

**Comment by Cadusredefine** [comment]
Gruppe bitte, also quasi als wahlmöglichkeit, wie e´medic, craftsman etc. sorry vielleicht wäre ein neues issue sinnvoller gewesen.

**Comment by maxbeier** [comment]
Ist beides drin. Passt es so?
