### ISSUE TITLE
Availabilities (GANTT)

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#37]
Neue Features:

- [x] Ändern des Zeitraums (und passend einfärben)
- [x] Auswahl passender Helfer und E-Mail-Sende-Möglichkeit
   Es werden alle verfügbaren (grün) Helfer selektiert. Die Liste kann verändert werden. Darunter wird ein Template-Text angezeigt und ein Absenden Knopf.
- [x] Filtermöglichkeit für Groups

**Comment by maxbeier** [comment]
So, die besprochenen Neuerungen bezüglich der Verfügbarkeiten sind drin. Du kannst die "Einstellungen" durch einen Klick auf das Logo öffnen (sollte durch die drei Punkte signalisiert werden, aber ich wahrscheinlich nicht intuitiv erfassbar).

![screen shot 2017-05-17 at 23 35 08](https://cloud.githubusercontent.com/assets/236774/26177442/e747e37e-3b59-11e7-91fc-9b523e1d1c17.png)

Hoffe, das hilft soweit.

**Comment by Cadusredefine** [comment]
super, danke dir!
