### ISSUE TITLE
Commitment Message einbauen

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#38]
- [x] Neues Feld anlegen
- [x] E-Mail an Helfer nach Zusage
- [x] Nachricht wird unter Mission für alle zusagenden Helfer angezeigt (nur diese!)

**Comment by maxbeier** [comment]
Möchtest du eigentlich auch eine E-Mail erhalten, wenn jemand bei einer Mission zusagt?

**Comment by maxbeier** [comment]
@Cadusredefine Möchtest du eigentlich auch eine E-Mail erhalten, wenn jemand bei einer Mission zusagt?

**Comment by maxbeier** [comment]
Ist drin. Schau mal bitte drüber, ob es so passt.

**Comment by Cadusredefine** [comment]
Bin bis Montag nicht in Deutschland - danach mach ich das. Lg 

Am 18. Mai 2017 16:14:23 MESZ schrieb Max Beier <notifications@github.com>:
>Ist drin. Schau mal bitte drüber, ob es so passt.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cadus/crewing/issues/38#issuecomment-302416317

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Cadusredefine** [comment]
ist die nachricht, die ich verfasst habe für die Teilnehmenden in der Einsatzplanung sichtbar? oder sehe nur ich die?

**Comment by maxbeier** [comment]
Sie ist nur für Teilnehmer sichtbar, die zugesagt (also auf "Ja" geklickt) haben.
