### ISSUE TITLE
Missionsbezogene Notizen zu Helfern

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#39]
Für die Koordinatorin einer Mission soll es die die Möglichkeit geben, (missionsbezogene) Notizen zu jeder Helferin zu hinterlegen. (Beispielsweise um zu tracken, welche Dokumente noch fehlen u.ä.)

Nachrichten können automatisch oder manuell gespeichert werden.

**Comment by maxbeier** [comment]
Ist drin. Passt es so?

**Comment by maxbeier** [comment]
Zur Benutzung: Änderungen an Kommentaren werden automatisch gespeichert, wenn eine Sekunde lang nicht mehr getippt wurde. Es gibt also keinen dedizierten Button zum Speichern.

**Comment by Cadusredefine** [comment]
passt!

**Comment by maxbeier** [comment]
- [ ] Textareas sollten sich automatisch der Größe des Inhalts anpassen
