### ISSUE TITLE
mission-seite

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#44]
die missionseite öffnet sich nicht mehr - zeigt permanent an, dass sie lädt, es passiert aber nichts mehr.

**Comment by maxbeier** [comment]
Hmpf, ja. Das System hat sich daran verschluckt, dass es in "2. Einsatz" eine Zuweisung ohne Person gab:

![screen shot 2017-06-13 at 12 26 06](https://user-images.githubusercontent.com/236774/27078322-96af66aa-5033-11e7-9623-c9d74c0c81e5.png)

Spiele gleich ein Update ein.

**Comment by maxbeier** [comment]
Update ist drin. Missionsseite funktioniert wieder.
