### ISSUE TITLE
Aktivierungslink wird nicht mehr gesendet

### ISSUE THREAD

**Issue by Cadusredefine** [cadus/crewing#47]
Habe von einigen Personen nun die Info, dass sie nach der Registrierung keinen Link zugesandt bekommen. Hab es gerade selber probiert, bei mir kommt auch nichts durch.

**Comment by maxbeier** [comment]
Hi,

❗️folgende URL nicht anklicken, ich lasse es gerade durchlaufen ❗️

es gibt jetzt eine neue URL , über die Admins die "crewing account created"-Mail an alle Volunteers schicken können, die den Link in ihrer Mail noch nicht geöffnet haben: https://cadus.f4.htw-berlin.de/api/volunteers/resendToken (damit die Mails nicht zu schnell verschickt werden, gibt es eine künstliche Verzögerung, weswegen das Ganze etwas dauert (derzeit knapp 12min)).

Für den Falls, dass ihr das ab und zu mal durchlaufen lassen wollt, um doch noch die eine oder andere zum nächsten Schritt zu bewegen.

P.S. Aktuell sind es 143 Adressen, die erneut benachrichtigt werden.

**Comment by maxbeier** [comment]
Ist durchgelaufen (13,2min). Im Test hat das Streaming funktioniert, auf dem Live-Server natürlich nicht 🙄 Also nicht wundern, dass die Seite leer bleibt, am Ende kommen dann alle Adressen, die benachrichtigt wurden.

**Comment by maxbeier** [comment]
Info an zukünftiges ich: `Content-Type` ist nicht gesetzt und `X-Content-Type-Options: nosniff` verhindert, dass der Inhalt als HTML erkannt wird 🚶
