### ISSUE TITLE
Entitäten "Projekt" und "Einsatzgebiet" hinzufügen

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#6]

**Comment by Cadusredefine** [comment]
"Boats- Seite" = Projects -  Dadurch würde sich ja bei Mission der Button "Boat"  in Projects umwandeln lassen, wäre auch sinnvoll.  Und darunter wäre es toll, wenn es noch die Option "Einsatzgebiet" gäbe. So hätten es wir eine vernünftige Übersicht von Projekt & Einsatzgebiet.
