### ISSUE TITLE
Löschen von Bildern ermöglichen

### ISSUE THREAD

**Issue by maxbeier** [cadus/crewing#9]
Nachfolger von #2

- https://github.com/keystonejs/keystone/issues/162
- https://github.com/keystonejs/keystone/issues/1382

**Comment by maxbeier** [comment]
@Cadusredefine Es ist jetzt möglich, Bilder zu löschen. Bitte von eurer Seite aus noch prüfen.

**Comment by Cadusredefine** [comment]
klappt, danke
